---
- name: Install Python packages
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - python
  - python-dev

- name: Download ez_setup
  get_url: url=http://peak.telecommunity.com/dist/ez_setup.py
           dest=~/ez_setup.py

- name: install ez_setup.py
  shell: python ez_setup.py
         chdir=~/

- name: Download pip
  get_url: url=https://bootstrap.pypa.io/get-pip.py
           dest=~/get-pip.py

- name: install get-pip.py
  shell: python get-pip.py
         chdir=~/

- name: Install Python-virtualenv packages
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - python-virtualenv
  - virtualenvwrapper



- name: update pip
  shell: pip install -U pip

- name: update setuptools
  shell: pip install -U setuptools

- name: update virtualenv
  shell: pip install -U virtualenv

- name: update virtualenvwrapper
  shell: pip install -U virtualenvwrapper