---
- name: drop old politics
  shell: iptables -P INPUT ACCEPT

- name: drop old rules
  shell: iptables -F

- name: Accept  conection RELATED,ESTABLISHED
  shell: iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

- name: Accept ssh conection port 22
  shell: iptables -A INPUT -p tcp --dport 22  -j ACCEPT

- name: Accept http conection port 80
  shell: iptables -A INPUT -p tcp --dport 80  -j ACCEPT

- name: Accept http conection to jenkins
  shell: iptables -A INPUT -p tcp --dport 8080  -j ACCEPT  

- name: Accept https conection port 443
  shell: iptables -A INPUT -p tcp --dport 443  -j ACCEPT

- name: localhost could conect anywhere
  shell: iptables -A INPUT -i lo -j ACCEPT

- name: Politic INPUT DROP
  shell: iptables -P INPUT DROP

# 445
# 139
# 53
# 631
# 111