---
- name: drop old politics
  shell: iptables -P INPUT ACCEPT

- name: drop old rules
  shell: iptables -F

- name: Accept  conection RELATED,ESTABLISHED
  shell: iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

- name: Accept ssh conection port 22
  shell: iptables -A INPUT -p tcp --dport 22  -j ACCEPT

- name: Accept conection port 5666 nagios monitoring #non default port
  shell: iptables -A INPUT -p tcp --dport 5666  -j ACCEPT

- name: Accept conection port {{firewall_port_up}}
  shell: iptables -A INPUT -p tcp --dport {{firewall_port_up}}  -j ACCEPT

- name: localhost could conect anywhere
  shell: iptables -A INPUT -i lo -j ACCEPT

- name: Politic INPUT DROP
  shell: iptables -P INPUT DROP