---
- name: remomve old java
  action: apt pkg={{item}} state=absent
  with_items:
    - java-common  
    - openjdk-6-jre-headless
    - openjdk-6-jre-lib

- apt_repository: repo='ppa:webupd8team/java'

- name: apt-get upgrade 
  action: apt update_cache=yes upgrade=yes

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: Install oracle-java8-installer
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - oracle-java8-installer
# sudo apt-get install oracle-java7-installer    

- name:  downloading the GPG signature
  shell: wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
  sudo: true

- name:  downloading the GPG signature
  shell: sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
  sudo: true

- name: Installing jenkins
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - jenkins
  sudo: true
