---
# Setup the apps
- include: essential.yml
  when: essential
- include: python.yml
  when: python
- include: local-essential.yml
  when: local-essential  
- include: rvm.yml
  when: rvm
- include: nginx_and_passenger.yml
  when: nginx_and_passenger
- include: jenkins.yml
  when: jenkins 
- include: postgresql.yml
  when: postgresql   


