- name: Install supervisor by pip
  shell: pip install -U supervisor

- name: create directory
  file: path=/usr/local/etc/ state=directory

- copy: src=supervisord.conf dest=/usr/local/etc/supervisord.conf owner=root group=root mode=644 force=yes
- copy: src=supervisord.sh dest=/etc/init.d/supervisord owner=root group=root mode=755

- name: Creo link para que se ejecute en el inicio de la pc
  file: src=/etc/init.d/supervisord  dest=/etc/init.d/S81supervisord  state=link
