---
- name: Install python-apt
  command: apt-get -y install python-apt

- name: Install aptitude (some ubuntus dont have it...)
  command: apt-get -y install aptitude

- name: apt-get upgrade 
  action: apt update_cache=yes upgrade=yes

- name: Install essential packages
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - git
  - mercurial
  - screen
  - bzip2
  - htop
  - vim
  - locate
  - nload
  - python-pycurl
  - zsh
  - apache2-utils

- name: Install build essential package
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - build-essential

