#https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-14-04
- name: Install VPN packages
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - openvpn 
  - easy-rsa

- name:  downloading the GPG signature
  shell: gunzip -c /usr/share/doc/openvpn/examples/sample-config-files/server.conf.gz > /etc/openvpn/server.conf

- name: keys Hardening "This will double the RSA key length used when generating server and client keys."
  lineinfile: dest=/etc/openvpn/server.conf  regexp="dh dh1024.pem" line="dh2048.pem"

- name: uncomment push "redirect-gateway def1 bypass-dhcp"
  lineinfile: dest=/etc/openvpn/server.conf  regexp='push ";redirect-gateway def1 bypass-dhcp"' line='push "redirect-gateway def1 bypass-dhcp"'

- name: uncomment dhcp-option DNS 208.67.222.222"
  lineinfile: dest=/etc/openvpn/server.conf  regexp='push ";dhcp-option DNS 208.67.222.222"' line='push "dhcp-option DNS 208.67.222.222"'

- name: uncomment push "dhcp-option DNS 208.67.220.220"
  lineinfile: dest=/etc/openvpn/server.conf  regexp=';push "dhcp-option DNS 208.67.220.220"' line='push "dhcp-option DNS 208.67.220.220"'

- name: uncomment ;user nobody
  lineinfile: dest=/etc/openvpn/server.conf  regexp=';user nobody' line='push "user nobody'
  lineinfile: dest=/etc/openvpn/server.conf  regexp=';group nogroup' line='push "group nogroup'

- name: share internet >> ip_forward
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: share internet  after reboot
  lineinfile: dest=/etc/sysctl.conf regexp="#net.ipv4.ip_forward=1" line="net.ipv4.ip_forward=1"

 #Creating a Certificate Authority and Server-Side Certificate & Key

- name: First copy over the Easy-RSA generation scripts.
  shell: cp -r /usr/share/easy-rsa/ /etc/openvpn
  shell: mkdir /etc/openvpn/easy-rsa/keys

#vim /etc/openvpn/easy-rsa/vars
#The variables below marked in red should be changed according to your preference.

#export KEY_COUNTRY="US"
#export KEY_PROVINCE="TX"
#export KEY_CITY="Dallas"
#export KEY_ORG="My Company Name"
#export KEY_EMAIL="sammy@example.com"
#export KEY_OU="MYOrganizationalUnit"