
- name: Install Nagios packages
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - nagios3 
  - nagios-nrpe-plugin

- name: creamos usuario nagios
  shell: usermod -a -G nagios www-data

- name: Cambiamos permisos
  shell: chmod -R g+x /var/lib/nagios3/
 
- name: sed...
  shell: sed -i 's/check_external_commands=0/check_external_commands=1/g' /etc/nagios3/nagios.cfg

# usermod -a -G nagios www-data
# chmod -R g+x /var/lib/nagios3/
# sed -i 's/check_external_commands=0/check_external_commands=1/g' /etc/nagios3/nagios.cfg 