---
- name: Download fail2ban
  get_url: url=https://codeload.github.com/fail2ban/fail2ban/tar.gz/0.8.13 dest=~/fail2ban-0.8.13.tar.gz

- name: createw folder /etc/fail2ban
  shell: mv ~/fail2ban-0.8.13.tar.gz /opt/fail2ban-0.8.13.tar.gz


- name: createw folder /etc/fail2ban
  shell: mkdir /etc/fail2ban
  ignore_errors: yes

- name: uncompress fail2ban-0.8.13.tar.gz
  command: tar xf fail2ban-0.8.13.tar.gz chdir=/opt/

- name: stat server fail2ban-server
  shell: /opt/fail2ban-0.8.13/fail2ban-server start

#
#- name: Install fail2ban - iptables-persistent using apt
#  apt: pkg={{ item }}
#       state=latest
#       install_recommends=yes
#       update_cache=yes
#  with_items:
#  - fail2ban
#  - iptables-persistent
