---
- name: setup ngios locales and timezone
  hosts: all
  gather_facts: false
  user: vagrant
  sudo: yes
  sudo_user: root
  vars_files:
    #- vars/nagios_cliente.yml
    - vars/nagios_server.yml
  roles:
   - nagios
    #role para instalar  en los clientes
   #- bobmaerten.nagios-nrpe-server
#https://galaxy.ansible.com/list#/roles/384

