---
- name: setup NFSEN
  hosts: all
  gather_facts: false
  user: vagrant
  sudo: yes
  sudo_user: root
  vars_files:
    - vars/default.yml
    - vars/nfsen.yml
  vars:
    ignoreip: 10.22.22.1
    mail_fail2band: ivan@admin.tesis
  roles:
   - fail2ban
#  - sfromm.nfsen
    #role para instalar  en los clientes
   #-  ansible-galaxy install sfromm.nfsen
#https://galaxy.ansible.com/list#/roles/384

