---
- name: setup Web server
  hosts: all
  gather_facts: false
  user: vagrant
  sudo: yes
  sudo_user: root
  vars_files:
    - vars/web.yml
  vars:
    server_name: web-server
    nagios_client: true
    nagios_server_ip: 10.22.22.10
  roles:
   #- essential
   - nagios
   #- nginx-passenger
